export const KAFKA_TOPICS = {
  CONTAINER_EVENTS: 'aegis.container.events',
  INCIDENT_DETECTED: 'aegis.incident.detected',
  LOGS_EXTRACTED: 'aegis.logs.extracted',
  AI_DIAGNOSIS_COMPLETED: 'aegis.ai.diagnosis.completed',
  REMEDIATION_STARTED: 'aegis.remediation.started',
  REMEDIATION_COMPLETED: 'aegis.remediation.completed',
  METRICS_SNAPSHOTS: 'aegis.metrics.snapshots',
  AUDIT_EVENTS: 'aegis.audit.events',
} as const;

export type KafkaTopic = typeof KAFKA_TOPICS[keyof typeof KAFKA_TOPICS];

export const KAFKA_CONSUMER_GROUPS = {
  WATCHMAN: 'aegis-watchman-group',
  INCIDENT: 'aegis-incident-group',
  AI: 'aegis-ai-group',
  REMEDIATION: 'aegis-remediation-group',
  DASHBOARD: 'aegis-dashboard-group',
  AUDIT: 'aegis-audit-group',
} as const;

export type KafkaConsumerGroupId = typeof KAFKA_CONSUMER_GROUPS[keyof typeof KAFKA_CONSUMER_GROUPS];

export const KAFKA_CONSUMER_SUBSCRIPTIONS: Record<KafkaConsumerGroupId, readonly KafkaTopic[]> = {
  [KAFKA_CONSUMER_GROUPS.WATCHMAN]: [KAFKA_TOPICS.CONTAINER_EVENTS, KAFKA_TOPICS.INCIDENT_DETECTED],
  [KAFKA_CONSUMER_GROUPS.INCIDENT]: [KAFKA_TOPICS.CONTAINER_EVENTS, KAFKA_TOPICS.INCIDENT_DETECTED, KAFKA_TOPICS.LOGS_EXTRACTED],
  [KAFKA_CONSUMER_GROUPS.AI]: [KAFKA_TOPICS.LOGS_EXTRACTED, KAFKA_TOPICS.AI_DIAGNOSIS_COMPLETED],
  [KAFKA_CONSUMER_GROUPS.REMEDIATION]: [KAFKA_TOPICS.REMEDIATION_STARTED, KAFKA_TOPICS.REMEDIATION_COMPLETED],
  [KAFKA_CONSUMER_GROUPS.DASHBOARD]: [
    KAFKA_TOPICS.CONTAINER_EVENTS,
    KAFKA_TOPICS.INCIDENT_DETECTED,
    KAFKA_TOPICS.LOGS_EXTRACTED,
    KAFKA_TOPICS.AI_DIAGNOSIS_COMPLETED,
    KAFKA_TOPICS.REMEDIATION_STARTED,
    KAFKA_TOPICS.REMEDIATION_COMPLETED,
    KAFKA_TOPICS.METRICS_SNAPSHOTS,
    KAFKA_TOPICS.AUDIT_EVENTS,
  ],
  [KAFKA_CONSUMER_GROUPS.AUDIT]: [KAFKA_TOPICS.AUDIT_EVENTS, KAFKA_TOPICS.METRICS_SNAPSHOTS, KAFKA_TOPICS.AI_DIAGNOSIS_COMPLETED, KAFKA_TOPICS.REMEDIATION_COMPLETED],
} as const;

export const KAFKA_SERVICE_NAME = 'aegis-backend' as const;